version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing tools..."
      - pip install --upgrade pip
      - pip install cfn-lint taskcat

  pre_build:
    commands:
      - echo "Running cfn-lint..."
      - cfn-lint cloudformation/nt548-network-ec2.yaml

  build:
    commands:
      - echo "Running taskcat..."
      - taskcat test run

artifacts:
  files:
    - '**/*'
