version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing tools..."
      - python -m venv venv
      - source venv/Scripts/activate
      - pip install --upgrade pip
      - python.exe -m pip install --upgrade pip
      - pip install cfn-lint

  pre_build:
    commands:
      - echo "Running cfn-lint..."
      - cfn-lint cloudformation/nt548-network-ec2.yaml --ignore-checks W6387,W6867

  build:
    commands:
      - echo "Running taskcat..."
      - taskcat test run

artifacts:
  files:
    - '**/*'
